name: My flutter workflow

on:
  pull_request:
    branches: ["master"]

jobs:
  lint:
    name: Clean Flutter , intsall dependencies and upgrade dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repo
        uses: subosito/flutter-action@v1
        with:
          flutter-version:  "3.7.7"
          channel: "stable"

      - run: flutter --version
      
      - name: Chekout Code
        uses: actions/checkout@v3

      - name: Get Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Clean Code
        run: flutter clean
      
      - name: Get Dependencies 
        run: flutter pub get

      - name: Upgrade Dependencies
        run: flutter pub upgrade


      
